execute pathogen#infect()
set t_Co=256
colorscheme badwolf
syntax on
filetype plugin indent on

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

set background=dark
set nocompatible
set mouse=a
set number
set relativenumber
set cursorline
set softtabstop=4
set shiftwidth=4
set expandtab
set wildmenu
set laststatus=2
set smartindent
set backspace=indent,eol,start

set incsearch
set hlsearch
set showcmd
set showmatch
set smartcase
set autowrite

" turn off search highlighting with ,space
nnoremap <leader><space> :nohlsearch<CR>
set foldenable		" enable folding
set foldlevelstart=10	" show first 10 folds by default
set foldnestmax=10	" max 10 nested folds
set foldmethod=indent	" fold based on indentation

" let mapleader="\"	" make comma leader instead of default \

